### PR TITLE
reformat server-core code

### PR DESCRIPTION
**Pull request by DebbieArita**

### CODE REVIEW

**Comment by qiarie** [comment]
@DebbieArita @sharon2719 Update to remove conflicts

**Review by ndegwamartin — APPROVED** [review]

**Review by ndegwamartin — CHANGES_REQUESTED** [review]
I think we can reformat in a new branch from `master` to avoid the large rebase footprint

**Comment by DebbieArita** [comment]
Agreed.

**Comment by ndegwamartin** [comment]
Closed by https://github.com/opensrp/opensrp-server-core/pull/593

**Pull request closed without merging**
